-- Initial schema for Supabase (Postgres)

create extension if not exists "pgcrypto";

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.experts (
  id bigint generated by default as identity primary key,
  name text not null,
  specialization text not null,
  experience integer not null default 0,
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  name text not null,
  email text not null,
  therapist_name text not null,
  session_date text not null,
  session_time text not null,
  notes text,
  status text not null default 'requested',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bookings_user_id_idx on public.bookings(user_id);
create index if not exists bookings_created_at_idx on public.bookings(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_bookings_updated_at on public.bookings;
create trigger set_bookings_updated_at
before update on public.bookings
for each row execute function public.set_updated_at();

